[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

# Create minigame state
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''DONT FIND THIS PLEASE THANK YOUif self.STATE == self.STATES.MENU then
            self:update_menu(dt)
        end'''
position = 'fter'
payload = '''if self.STATE == self.STATES.FOOBAR_MINIGAME then
	self:update_foobar_minigame(dt)
end'''
match_indent = true

